
# Get list
GET http://localhost:8080/books
Content-Type: application/json

###

# Get list
GET http://localhost:8080/books?searchQuery=book 1
Content-Type: application/json

###

# Add book
POST http://localhost:8080/books
Content-Type: application/json

{
  "name": "name",
  "author": "Gogol 1"
}
###

# Get book by id
GET http://localhost:8080/books/533d6d03-e34b-4675-9586-af85d8b55c88
Content-Type: application/json

###

# Update book
PUT http://localhost:8080/books/0aeeb161-0494-44da-8547-3c21572d049b
Content-Type: application/json

{
  "name": "book 2 update",
  "author": ""
}
###

###
# Delete book
DELETE http://localhost:8080/books/e4d287e1-9a1e-4ac9-b537-a53bc845f313
Content-Type: application/json

###

# Get list of readers
GET http://localhost:8080/readers
Content-Type: application/json

###
# Add reader
POST http://localhost:8080/readers
Content-Type: application/json

{
  "name": "reader 1"
}

###

# Get reader by id
GET http://localhost:8080/readers/dd9ffe45-dc1a-4607-8eb4-ce3d8672a2fa
Content-Type: application/json

###

# Update reader
PUT http://localhost:8080/readers/cca93c8a-90c4-4ac6-bb67-686590ddd657
Content-Type: application/json

{
  "name": "reader 1 update"
}
###

###
# Delete reader
DELETE http://localhost:8080/readers/a75dcdbe-26bc-4a06-b59d-9e19dc9f62cf
Content-Type: application/json

###


# Start Read
POST http://localhost:8080/readers/b198137a-0ce2-4dec-aa32-c4b410531f29/takeBook
Content-Type: application/json

{
  "bookId": "aee376e5-039e-47e7-b187-a68a7eb069e0"
}

###

# Finish Read
POST http://localhost:8080/readers/b198137a-0ce2-4dec-aa32-c4b410531f29/returnBook
Content-Type: application/json

{
  "bookId": "aee376e5-039e-47e7-b187-a68a7eb069e0"
}

###

# Popularity
GET http://localhost:8080/books/aee376e5-039e-47e7-b187-a68a7eb069e0/popularity
Content-Type: application/json

###

# Averagetime
GET http://localhost:8080/books/aee376e5-039e-47e7-b187-a68a7eb069e0/averagetime
Content-Type: application/json

###